name: tethered
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  algolia: ^1.0.1
  animations: ^2.0.1
  badges: ^2.0.1
  cached_network_image: ^3.0.0
  carousel_slider: ^3.0.0
  cloud_firestore: ^2.2.2
  cloud_functions: ^3.0.0
  cupertino_icons: ^1.0.2
  firebase_analytics: ^8.1.2
  firebase_auth: ^1.0.3
  firebase_core: ^1.0.3
  firebase_storage: ^10.0.1
  flappy_search_bar: ^1.7.2
  floating_bottom_navigation_bar: ^1.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_hooks: null
  flutter_markdown: ^0.6.4
  flutter_quill: ^1.1.8
  flutter_snake_navigationbar: ^0.5.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  flutter_test:
    sdk: flutter
  freezed_annotation: null
  get: ^4.1.4
  get_it: ^7.1.3
  google_fonts: ^2.0.0
  hooks_riverpod: ^0.14.0+4
  http: ^0.13.3
  image_cropper: null
  infinite_scroll_pagination: ^3.1.0
  injectable: ^1.0.4
  notus: ^0.1.5
  path_provider: ^2.0.2
  provider: ^5.0.0
  pull_to_refresh: ^2.0.0
  settings_ui: ^1.0.0
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: null
  freezed: null
  injectable_generator: ^1.0.4
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: TetheredIcons
      fonts:
        - asset: assets/fonts/TetheredIcons.ttf
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/markdown/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
